language: node_js
node_js:
    - 11.6.0
cache: npm

install:
    - npm install

script:
    - npm test
    - npm run build

deploy:
    provider: pages
    skip-cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
        branch: master